#! /usr/bin/env bash
inbox="/home/thyriaen/Work/sync/JM-WORK/99 Diverses/Posteingang/"
files=$(find "$inbox" -maxdepth 1 -type f | wc -l)
if [[ $files -eq 0 ]]; then
	printf "<span foreground='#94B852'>  %s</span>" "$files"
else
	printf "<span foreground='#B85261'>  %s</span>" "$files"
fi


# printf "<span foreground='blue'>Blue text</span> is <i>cool</i>!"

