#! /usr/bin/env bash
inbox="/home/thyriaen/Work/01 Sync/JM-WORK/99 Diverses/Posteingang"
files=$(find "$inbox" -maxdepth 1 -type f | wc -l)
if [[ $files -eq 0 ]]; then
	printf "<span fgcolor='#94B852'><span size='16pt'>󰚇 </span>%s</span>" "$files"
else
	printf "<span fgcolor='#B85261'><span size='16pt'>󱉳 </span>%s</span>" "$files"
fi


# printf "<span foreground='blue'>Blue text</span> is <i>cool</i>!"

