#!/bin/bash

# fulltime:         300 min/d - 150 h/m
# really nice:      256 min/d - 128 h/m
# proper income:    192 min/d -  96 h/m
# absolute minimum  160 min/d -  80 h/m

work_per_day=$((120 * 128))

# Zeit hübsch ausgeben
print_time() {
  local secs=$1
  local color=$2
  local icon=$3

  local formatted
  formatted=$(date -u -d "@$secs" +"%-H:%M")
  printf "<span fgcolor='%s'>%s</span>" "$color" "$formatted"
}

# Watson-Zeit in Sekunden holen (Argument z.B. -d oder -m)
watson_time() {
  local range=$1
  watson report "$range" -c -j \
    | grep '"time"' \
    | tail -n1 \
    | grep -oE '[0-9]+' \
    | head -n1 \
    | tr -d '\n'
}

# Tage im aktuellen Monat
days_in_month() {
  date -d "$(date +%Y-%m-01) +1 month -1 day" +%d
}

# Verbleibende Tage im aktuellen Monat (inkl. heute)
days_remaining_in_month() {
  local end now
  end=$(date -d "$(date +%Y-%m-01) +1 month -1 day" +%s)
  now=$(date +%s)
  echo $(( (end - now) / 86400 + 1 ))
}

worked_today=$(watson_time -d)
left_today=$(( work_per_day - worked_today ))

# 1. Ziel: Tagesziel schaffen
if (( left_today >= 0 )); then
  print_time "$left_today" '#B85261' '󰃖 '
  exit 0
fi

# 2. Ziel: Monatsziel linear auf Resttage verteilen
worked_month=$(watson_time -m)
daysInMonth=$(days_in_month)
totalInMonth=$(( daysInMonth * work_per_day ))
daysRemaining=$(days_remaining_in_month)

monthlyTarget=$(( (totalInMonth - worked_month + worked_today) / daysRemaining ))
left_today_target=$(( monthlyTarget - worked_today ))

if (( left_today_target >= 0 )); then
  print_time "$left_today_target" '#B85294' '󰃖 '
  exit 0
fi

# 3. Ziel: rückwirkend „sollte bis heute im Monat“
monthday=$(date +%-d)
monthly_left_today=$(( work_per_day * monthday - worked_month ))

if (( monthly_left_today >= 0 )); then
  print_time "$monthly_left_today" '#7652B8' '󰃖 '
else
  # Überschuss im Monat
  print_time "${monthly_left_today#-}" '#94B852' '󰃗 '
fi
