#!/bin/bash
num=$(echo $((1 + $RANDOM % 500)))

cat /home/thyriaen/.config/eww/quotes/quotes.json | jq --arg num "$num" ".[$num]" | jq -r ".text" > /home/thyriaen/.config/eww/quotes/quote
cat /home/thyriaen/.config/eww/quotes/quotes.json | jq --arg num "$num" ".[$num]" | jq -r ".author" > /home/thyriaen/.config/eww/quotes/author