
RUSTICL_ENABLE=radeonsi

NNN_FIFO=/tmp/nnn.fifo
NNN_PLUG=p:preview-tui;d:drag;o:xdgdefault
NNN_BATTHEME="Monokai Extended"

TERMINAL=kitty
SHELL=/usr/bin/zsh
EDITOR=vi
VISUAL=vi

GTK_USE_PORTAL=1
XDG_CONFIG_HOME=${HOME}/.config
PATH=${HOME}/.local/bin:${PATH}

