$MONITOR = DP-3,3440x1440@165,0x0,1,vrr,0
$KEEPASS_MOVE = 2344 800
$KEEPASS_WIDTH = 1032
$KEEPASS_HEIGHT = 576
$CENTER_SINGLE_MASTER = 1
$NNN_WIDTH = 1720
$NNN_HEIGHT = 1152
$SIDETERM_SIZE = 960 720
$SIDETERM_MOVE = 137 662
$SIDEBAR_SIZE = 352 416
$MATE_CALC_MOVE = 2749 84
$DRAGON_MOVE = 3240 700

exec-once = easyeffects --gapplication-service

bind = , XF86MonBrightnessDown, exec, ddcutil setvcp 10 0
bind = , XF86MonBrightnessUp, exec, ddcutil setvcp 10 60
