$MONITOR = eDP-1,1920x1080@60,0x0,1
$KEEPASS_MOVE = 1280 584
$CENTER_SINGLE_MASTER = 0
$NNN_SIZE = 66% 80%
$SIDETERM_SIZE = 45% 50%
$SIDETERM_MOVE = 7% 46%

exec-once = light -N 1

gesture = 3, horizontal, workspace

bind = , XF86MonBrightnessDown, exec, light -U 10
bind = , XF86MonBrightnessUp, exec, light -A 10
