$MONITOR = eDP-1,1920x1080@60,0x0,1
$KEEPASS_MOVE = 1280 584
$KEEPASS_WIDTH = 576
$KEEPASS_HEIGHT = 432
$CENTER_SINGLE_MASTER = 0
$NNN_WIDTH = 1267
$NNN_HEIGHT = 864
$SIDETERM_SIZE = 864 540
$SIDETERM_MOVE = 134 497
$MATE_CALC_SIZE = 576 432
$MATE_CALC_MOVE = 1306 16
$DRAGON_MOVE = 1766 540
$POMOTROID_SIZE = 192 108
$POMOTROID_MOVE_IDLE = 77 130
$POMOTROID_MOVE_ACTIVE = 461 259

exec-once = light -N 1

gesture = 3, horizontal, workspace

bind = , XF86MonBrightnessDown, exec, light -U 10
bind = , XF86MonBrightnessUp, exec, light -A 10
