general {
    hide_cursor = true
    grace = 0
}

animations {
    enabled = true
    bezier = unlock, 0.22, 1, 0.36, 1
    animation = fadeIn, 1, 4, unlock
    animation = fadeOut, 1, 5, unlock
    animation = inputFieldDots, 1, 2, unlock
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
    brightness = 0.70
}

input-field {
    monitor =
    size = 320, 64
    position = 0, -120
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.28
    dots_spacing = 0.18
    outer_color = rgb(7652B8)
    inner_color = rgb(18191A)
    font_color = rgb(EDE7F6)
    fade_on_empty = false
    placeholder_text =
    fail_text =
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    position = 0, 20
    halign = center
    valign = center
    color = rgb(EDE7F6)
    font_family = M PLUS 1
    font_size = 72
}
