#!/usr/bin/env sh

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
# shellcheck disable=SC2034
resp=c

if [ -s "$selection" ]; then
    sed -z 's|'"$PWD/"'||g' < "$selection" | xargs -0 dragon -i --and-exit -A &
else
    if [ -n "$1" ] && [ -e "$1" ]; then
        dragon -i --and-exit "$1" &
    fi
fi
